language: rust
cache: cargo
before_script:
- cargo update || true
rust:
  - stable
  - 1.33.0
  - 1.32.0
  - 1.31.1
  - beta
  - nightly

matrix:
  include:
    - rust: stable
      env: TASK=rustfmt
      before_script: rustup component add rustfmt
      script: cargo fmt -- --check
  allow_failures:
    - rust: nightly
